language: node_js
node_js:
  - "12"
script: 
  - npm run lint
  - npm run test
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
branches:
  only:
    - master